# Generated by Django 4.2.2 on 2023-06-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("document_number", models.CharField(max_length=50)),
                ("birthdate", models.DateField()),
                ("created_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
