# Generated by Django 4.2.2 on 2023-06-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="document_number",
            field=models.CharField(max_length=51),
        ),
    ]
